#@ load("@ytt:data", "data")
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: makingx+cert-manager@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        azuredns:
          clientID: #@ data.values.azure.client_id
          clientSecretSecretRef:
            name: azuredns-config
            key: client-secret
          subscriptionID: #@ data.values.azure.subscription_id
          tenantID: #@ data.values.azure.tenant_id
          resourceGroupName: #@ data.values.azure.resource_group_name
          hostedZoneName: #@ data.values.azure.hosted_zone_name
          environment: #@ data.values.azure.environment
